import { DisList, RewardProps } from "@/types/dashboard";
import { InventoryProps } from "@/types/dashboard";

const distributorList: DisList[] = [
  {
    name: "David Wilson",
    lastModified: "22 Jan 2022",
    location: "Lagos",
    category: "Main distributor",
    performance: "67%",
    id:'1'
  },
  {
    name: "John Smith",
    lastModified: "15 Feb 2023",
    location: "Benue",
    category: "Main distributor",
    performance: "67%",
    id:'2'
  },
  {
    name: "Mary Johnson",
    lastModified: "10 Mar 2021",
    location: "Enugu",
    category: "Main distributor",
    performance: "72%",
    id:'3'
  },
  {
    name: "James Brown",
    lastModified: "05 Dec 2022",
    location: "Abia",
    category: "Main distributor",
    performance: "67%",
    id:'4'
  },
  {
    name: "Emily Davis",
    lastModified: "18 Jul 2022",
    location: "Osun",
    category: "Main distributor",
    performance: "70%",
    id:'5'
  },
  {
    name: "Michael Wilson",
    lastModified: "25 Aug 2021",
    location: "Ondo",
    category: "Main distributor",
    performance: "67%",
    id:'6'
  },
  {
    name: "Linda Miller",
    lastModified: "03 Feb 2023",
    location: "Delta",
    category: "Main distributor",
    performance: "75%",
    id:'7'
  },
  {
    name: "Robert Taylor",
    lastModified: "11 Nov 2022",
    location: "Benin",
    category: "Main distributor",
    performance: "67%",
    id:'8'
  },
  {
    name: "Patricia Anderson",
    lastModified: "28 Jan 2022",
    location: "Lagos",
    category: "Main distributor",
    performance: "74%",
    id:'9'
  },
  {
    name: "William Martinez",
    lastModified: "06 Apr 2023",
    location: "Port-harcourt",
    category: "Main distributor",
    performance: "71%",
    id:'10'
  },
  {
    name: "Jessica Thomas",
    lastModified: "20 Sep 2021",
    location: "Ibadan",
    category: "Main distributor",
    performance: "67%",
    id:'11'
  },
];

const subDistributorList: DisList[] = [
  {
    name: "Amina Bello",
    lastModified: "22 Jan 2022",
    location: "Kano",
    category: "Subdistributor",
    performance: "76%",
    id: "1",
  },
  {
    name: "Chijioke Okafor",
    lastModified: "12 Feb 2023",
    location: "Abuja",
    category: "Subdistributor",
    performance: "78%",
    id: "2",
  },
  {
    name: "Ngozi Eze",
    lastModified: "18 Mar 2022",
    location: "Enugu",
    category: "Subdistributor",
    performance: "10%",
    id: "3",
  },
  {
    name: "Bola Adebayo",
    lastModified: "05 Dec 2022",
    location: "Ogun",
    category: "Subdistributor",
    performance: "77%",
    id: "4",
  },
  {
    name: "Ifeoma Nwachukwu",
    lastModified: "28 Jun 2021",
    location: "Imo",
    category: "Subdistributor",
    performance: "75%",
    id: "5",
  },
  {
    name: "Tunde Adeyemi",
    lastModified: "30 Jul 2022",
    location: "Ekiti",
    category: "Subdistributor",
    performance: "12%",
    id: "6",
  },
  {
    name: "Chuka Obi",
    lastModified: "15 Aug 2022",
    location: "Anambra",
    category: "Subdistributor",
    performance: "79%",
    id: "7",
  },
  {
    name: "Sarah Olayemi",
    lastModified: "03 Jan 2023",
    location: "Lagos",
    category: "Subdistributor",
    performance: "13%",
    id: "8",
  },
  {
    name: "Umar Sani",
    lastModified: "10 Sep 2021",
    location: "Kaduna",
    category: "Subdistributor",
    performance: "78%",
    id: "9",
  },
  {
    name: "Oluwaseun Akinyemi",
    lastModified: "18 Mar 2023",
    location: "Port-Harcourt",
    category: "Subdistributor",
    performance: "11%",
    id: "10",
  },
  {
    name: "Rashida Mustapha",
    lastModified: "22 Oct 2022",
    location: "Jos",
    category: "Subdistributor",
    performance: "77%",
    id: "11",
  },
];


const inventoryManagement: InventoryProps[] = [
  {
    Product: "Teem",
    EntryD: "08 Mar 2025",
    BatchID: "20199",
    QuantityS: 1000,
    UnitP: 700,
    // AmountS: 140000,
    quantityS: 255,
    // AmountSold: 28000,
    QuantityR: 160,
    // remainingA: 112000,
  },
  {
    Product: "Pepsi",
    EntryD: "08 Feb 2025",
    BatchID: "20199",
    QuantityS: 2000,
    UnitP: 700,
    // AmountS: 140000,
    quantityS: 300,
    // AmountSold: 28000,
    QuantityR: 160,
    // remainingA: 112000,
  },
  {
    Product: "Mountain",
    EntryD: "08 Mar 2025",
    BatchID: "20200",
    QuantityS: 1180,
    UnitP: 750,
    // AmountS: 135000,
    quantityS: 470,
    // AmountSold: 27000,
    QuantityR: 144,
    // remainingA: 108000,
  },
  {
    Product: "Teem",
    EntryD: "08 Feb 2025",
    BatchID: "20201",
    QuantityS: 2120,
    UnitP: 650,
    // AmountS: 143000,
    quantityS: 200,
    // AmountSold: 28600,
    QuantityR: 176,
    // remainingA: 114400,
  },
  {
    Product: "Mirinda",
    EntryD: "08 Mar 2025",
    BatchID: "20202",
    QuantityS: 1150,
    UnitP: 670,
    // AmountS: 100500,
    quantityS: 600,
    // AmountSold: 20100,
    QuantityR: 120,
    // remainingA: 80400,
  },
  {
    Product: "Aquafina",
    EntryD: "08 Feb 2025",
    BatchID: "20203",
    QuantityS: 2150,
    UnitP: 690,
    // AmountS: 172500,
    quantityS: 550,
    // AmountSold: 34500,
    QuantityR: 200,
    // remainingA: 138000,
  },
  {
    Product: "Mountain",
    EntryD: "08 Mar 2025",
    BatchID: "20204",
    QuantityS: 1190,
    UnitP: 710,
    // AmountS: 135900,
    quantityS: 670,
    // AmountSold: 27180,
    QuantityR: 152,
    // remainingA: 107520,
  },
  {
    Product: "Mirinda",
    EntryD: "08 Feb 2025",
    BatchID: "20205",
    QuantityS: 1210,
    UnitP: 680,
    // AmountS: 142800,
    quantityS: 330,
    // AmountSold: 28560,
    QuantityR: 168,
    // remainingA: 113280,
  },
  {
    Product: "Pepsi",
    EntryD: "08 Mar 2025",
    BatchID: "20206",
    QuantityS: 2010,
    UnitP: 700,
    // AmountS: 140000,
    quantityS: 490,
    // AmountSold: 28000,
    QuantityR: 160,
    // remainingA: 112000,
  },
  {
    Product: "Mountain",
    EntryD: "08 Feb 2025",
    BatchID: "20207",
    QuantityS: 1710,
    UnitP: 740,
    // AmountS: 125800,
    quantityS: 300,
    // AmountSold: 25160,
    QuantityR: 136,
    // remainingA: 100640,
  },
  {
    Product: "Aquafina",
    EntryD: "08 Mar 2025",
    BatchID: "20208",
    QuantityS: 2130,
    UnitP: 660,
    // AmountS: 151800,
    quantityS: 700,
    // AmountSold: 30360,
    QuantityR: 184,
    // remainingA: 121440,
  },
];


const miniInventoryList: InventoryProps[] = [
  {
    Product: "Pepsi",
    EntryD: "22 Jan 2022",
    BatchID: "20199",
    QuantityS: 200,
    UnitP: 700,
    // AmountS: 140000,
    quantityS: 300,
    // AmountSold: 28000,
    QuantityR: 160,
    // remainingA: 112000,
  },
  {
    Product: "Pepsi",
    EntryD: "22 Jan 2022",
    BatchID: "20199",
    QuantityS: 200,
    UnitP: 700,
    // AmountS: 140000,
    quantityS: 300,
    // AmountSold: 28000,
    QuantityR: 160,
    // remainingA: 112000,
  },
];

const product:string[] = [
  'Pepsi', '7UP', 'Mirinda','Mountain', 'Teem', 'Lipton', 'Aquafina'
]

const retailerList: DisList[] = [
  {
    name: "Grace Olamide",
    lastModified: "10 Jan 2023",
    location: "Lagos",
    category: "Retailer",
    performance: "9%",
    id: "1",
  },
  {
    name: "Micheal Ogbu",
    lastModified: "15 Feb 2022",
    location: "Abuja",
    category: "Retailer",
    performance: "12%",
    id: "2",
  },
  {
    name: "Paul Okeke",
    lastModified: "20 Nov 2021",
    location: "Kaduna",
    category: "Retailer",
    performance: "8%",
    id: "3",
  },
  {
    name: "Lola Olamide",
    lastModified: "06 Dec 2022",
    location: "Ogun",
    category: "Retailer",
    performance: "10%",
    id: "4",
  },
  {
    name: "Victor Ajayi",
    lastModified: "22 Jul 2021",
    location: "Enugu",
    category: "Retailer",
    performance: "6%",
    id: "5",
  },
  {
    name: "Oluwatosin Adebanjo",
    lastModified: "11 Mar 2023",
    location: "Ekiti",
    category: "Retailer",
    performance: "15%",
    id: "6",
  },
  {
    name: "Nneka Eze",
    lastModified: "14 Sep 2021",
    location: "Imo",
    category: "Retailer",
    performance: "7%",
    id: "7",
  },
  {
    name: "Chidi Nwosu",
    lastModified: "29 Oct 2022",
    location: "Port-Harcourt",
    category: "Retailer",
    performance: "13%",
    id: "8",
  },
  {
    name: "Fola Akinpelu",
    lastModified: "10 Aug 2022",
    location: "Anambra",
    category: "Retailer",
    performance: "11%",
    id: "9",
  },
  {
    name: "Adewale Abiola",
    lastModified: "19 Mar 2023",
    location: "Jos",
    category: "Retailer",
    performance: "9%",
    id: "10",
  },
  {
    name: "Sofia Ojo",
    lastModified: "12 Nov 2021",
    location: "Kano",
    category: "Retailer",
    performance: "8%",
    id: "11",
  },
];

const rewardRecipients: RewardProps = {
  platinum: [
    {
      name: "Ife OluwaYelu",
      location: "Lagos",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Tunde Adebayo",
      location: "Abuja",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Kemi Ajayi",
      location: "Port Harcourt",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Emeka Nwankwo",
      location: "Enugu",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Ngozi Okoro",
      location: "Benin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Chinedu Okechukwu",
      location: "Ibadan",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Abdul Hassan",
      location: "Kaduna",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Micheal Thompson",
      location: "Ilorin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Rahila Bello",
      location: "Zaria",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
    {
      name: "Daniel Olorunfemi",
      location: "Oyo",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 90}`,
    },
  ],
  diamond: [
    {
      name: "Tunde Adebayo",
      location: "Abuja",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Kemi Ajayi",
      location: "Port Harcourt",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Emeka Nwankwo",
      location: "Enugu",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Ngozi Okoro",
      location: "Benin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Chinedu Okechukwu",
      location: "Ibadan",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Abdul Hassan",
      location: "Kaduna",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Micheal Thompson",
      location: "Ilorin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Rahila Bello",
      location: "Zaria",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
    {
      name: "Daniel Olorunfemi",
      location: "Oyo",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 80}`,
    },
  ],
  gold: [
    {
      name: "Ife OluwaYelu",
      location: "Lagos",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Tunde Adebayo",
      location: "Abuja",
      rank: "Secondary distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Kemi Ajayi",
      location: "Port Harcourt",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Emeka Nwankwo",
      location: "Enugu",
      rank: "Secondary distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Ngozi Okoro",
      location: "Benin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Chinedu Okechukwu",
      location: "Ibadan",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Abdul Hassan",
      location: "Kaduna",
      rank: "Secondary distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Micheal Thompson",
      location: "Ilorin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Rahila Bello",
      location: "Zaria",
      rank: "Secondary distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
    {
      name: "Daniel Olorunfemi",
      location: "Oyo",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 70}`,
    },
  ],
  incentive: [
    {
      name: "Ngozi Okoro",
      location: "Benin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 50}`,
    },
    {
      name: "Chinedu Okechukwu",
      location: "Ibadan",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 50}`,
    },
    {
      name: "Abdul Hassan",
      location: "Kaduna",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 50}`,
    },
    {
      name: "Micheal Thompson",
      location: "Ilorin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 50}`,
    },
    {
      name: "Rahila Bello",
      location: "Zaria",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 50}`,
    },
    {
      name: "Daniel Olorunfemi",
      location: "Oyo",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 11) + 50}`,
    },
  ],
  intervention: [
    {
      name: "Kemi Ajayi",
      location: "Port Harcourt",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 30) + 10}`,
    },
    {
      name: "Emeka Nwankwo",
      location: "Enugu",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 30) + 10}`,
    },
    {
      name: "Ngozi Okoro",
      location: "Benin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 30) + 10}`,
    },
    {
      name: "Chinedu Okechukwu",
      location: "Ibadan",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 30) + 10}`,
    },
    {
      name: "Abdul Hassan",
      location: "Kaduna",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 30) + 10}`,
    },
    {
      name: "Micheal Thompson",
      location: "Ilorin",
      rank: "Main distributor",
      performance: `${Math.floor(Math.random() * 30) + 10}`,
    },
  ],
};

const recallDemo = [
  {
    product: "Pepsi",
    batch: "20020",
    quantity: "400",
    price: "N550",
    entry: "22 Jan, 2022",
  },
  {
    product: "7UP",
    batch: "20021",
    quantity: "350",
    price: "N600",
    entry: "10 Feb, 2022",
  },
  {
    product: "Teem",
    batch: "20022",
    quantity: "500",
    price: "N450",
    entry: "15 Mar, 2022",
  },
  {
    product: "Lipton",
    batch: "20023",
    quantity: "200",
    price: "N500",
    entry: "5 Apr, 2022",
  },
  {
    product: "Mirinda",
    batch: "20024",
    quantity: "600",
    price: "N480",
    entry: "20 May, 2022",
  },
  {
    product: "Mountain",
    batch: "20025",
    quantity: "550",
    price: "N650",
    entry: "12 Jun, 2022",
  },
  {
    product: "Pepsi",
    batch: "20026",
    quantity: "450",
    price: "N520",
    entry: "2 Jul, 2022",
  },
  {
    product: "Aquafina",
    batch: "20027",
    quantity: "400",
    price: "N580",
    entry: "18 Aug, 2022",
  },
  {
    product: "7UP",
    batch: "20028",
    quantity: "500",
    price: "N460",
    entry: "25 Sep, 2022",
  },
  {
    product: "Mountain",
    batch: "20029",
    quantity: "350",
    price: "N490",
    entry: "7 Oct, 2022",
  },
];



export { distributorList, inventoryManagement, subDistributorList, retailerList, miniInventoryList, product, rewardRecipients, recallDemo };