export type ChartDataType = {
  period: string;
  sales: number;
}[];

export const chartData = [
  { period: "January", sales: 222 },
  { period: "February", sales: 97 },
  { period: "March", sales: 167 },
  { period: "April", sales: 242 },
  { period: "May", sales: 373 },
  { period: "June", sales: 301 },
  { period: "July", sales: 245 },
  { period: "August", sales: 409 },
  { period: "September", sales: 59 },
  { period: "October", sales: 261 },
  { period: "November", sales: 327 },
  { period: "December", sales: 292 },
];
export const companyEmplyCountValues = [
  "1-10",
  "11-50",
  "51-200",
  "201-1000",
  "1001+",
];

export const industry = [
  "Agriculture",
  "Construction",
  "Financial services",
  "Healthcare",
  "Oil and gas",
  "Consumer goods",
  "Information and Communications Technology",
];

export const distributorList = [
  {
    fullName: "David Wilson",
    lastModified: "22 Jan 2022",
    location: "Lagos",
    userType: "Main distributor",
    salesPerformance: "5%",
    id: "1",
  },
  {
    fullName: "John Smith",
    lastModified: "15 Feb 2023",
    location: "Benue",
    userType: "Main distributor",
    salesPerformance: "8%",
    id: "2",
  },
  {
    fullName: "Mary Johnson",
    lastModified: "10 Mar 2021",
    location: "Enugu",
    userType: "Main distributor",
    salesPerformance: "12%",
    id: "3",
  },
  {
    fullName: "James Brown",
    lastModified: "05 Dec 2022",
    location: "Abia",
    userType: "Main distributor",
    salesPerformance: "7%",
    id: "4",
  },
  {
    fullName: "Emily Davis",
    lastModified: "18 Jul 2022",
    location: "Osun",
    userType: "Main distributor",
    salesPerformance: "10%",
    id: "5",
  },
  {
    fullName: "Michael Wilson",
    lastModified: "25 Aug 2021",
    location: "Ondo",
    userType: "Main distributor",
    salesPerformance: "6%",
    id: "6",
  },
  {
    fullName: "Linda Miller",
    lastModified: "03 Feb 2023",
    location: "Delta",
    userType: "Main distributor",
    salesPerformance: "15%",
    id: "7",
  },
  {
    fullName: "Robert Taylor",
    lastModified: "11 Nov 2022",
    location: "Benin",
    userType: "Main distributor",
    salesPerformance: "9%",
    id: "8",
  },
  {
    fullName: "Patricia Anderson",
    lastModified: "28 Jan 2022",
    location: "Lagos",
    userType: "Main distributor",
    salesPerformance: "14%",
    id: "9",
  },
  {
    fullName: "William Martinez",
    lastModified: "06 Apr 2023",
    location: "Port-harcourt",
    userType: "Main distributor",
    salesPerformance: "11%",
    id: "10",
  },
  {
    fullName: "Jessica Thomas",
    lastModified: "20 Sep 2021",
    location: "Ibadan",
    userType: "Main distributor",
    salesPerformance: "4%",
    id: "11",
  },
];

export const subDistributorList = [
  {
    fullName: "Amina Bello",
    lastModified: "22 Jan 2022",
    location: "Kano",
    userType: "Subdistributor",
    salesPerformance: "6%",
    id: "1",
  },
  {
    fullName: "Chijioke Okafor",
    lastModified: "12 Feb 2023",
    location: "Abuja",
    userType: "Subdistributor",
    salesPerformance: "8%",
    id: "2",
  },
  {
    fullName: "Ngozi Eze",
    lastModified: "18 Mar 2022",
    location: "Enugu",
    userType: "Subdistributor",
    salesPerformance: "10%",
    id: "3",
  },
  {
    fullName: "Bola Adebayo",
    lastModified: "05 Dec 2022",
    location: "Ogun",
    userType: "Subdistributor",
    salesPerformance: "7%",
    id: "4",
  },
  {
    fullName: "Ifeoma Nwachukwu",
    lastModified: "28 Jun 2021",
    location: "Imo",
    userType: "Subdistributor",
    salesPerformance: "5%",
    id: "5",
  },
  {
    fullName: "Tunde Adeyemi",
    lastModified: "30 Jul 2022",
    location: "Ekiti",
    userType: "Subdistributor",
    salesPerformance: "12%",
    id: "6",
  },
  {
    fullName: "Chuka Obi",
    lastModified: "15 Aug 2022",
    location: "Anambra",
    userType: "Subdistributor",
    salesPerformance: "9%",
    id: "7",
  },
  {
    fullName: "Sarah Olayemi",
    lastModified: "03 Jan 2023",
    location: "Lagos",
    userType: "Subdistributor",
    salesPerformance: "13%",
    id: "8",
  },
  {
    fullName: "Umar Sani",
    lastModified: "10 Sep 2021",
    location: "Kaduna",
    userType: "Subdistributor",
    salesPerformance: "8%",
    id: "9",
  },
  {
    fullName: "Oluwaseun Akinyemi",
    lastModified: "18 Mar 2023",
    location: "Port-Harcourt",
    userType: "Subdistributor",
    salesPerformance: "11%",
    id: "10",
  },
  {
    fullName: "Rashida Mustapha",
    lastModified: "22 Oct 2022",
    location: "Jos",
    userType: "Subdistributor",
    salesPerformance: "7%",
    id: "11",
  },
];

