import type { Metadata } from "next";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

export const metadata: Metadata = {
	title: "Excite Business",
	description: "Generated by create next app",
};

export default function DashBoardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className={`relative`}>
			<Navbar />
			<div className="h-auto">{children}</div>
			<Footer />
		</main>
	);
}
