import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Excite Trade",
  description: "Generated by create next app",
};

const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} text-[#171717] text-sm xl:text-base antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
