import type { Metadata } from "next";
import SideBar from "@/components/dashboard/layout/SideBar";
import Header from "@/components/dashboard/layout/Header";

export const metadata: Metadata = {
  title: "Excite Business Agent Dashboard",
  description: "Generated by create next app",
};


export default function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`relative`}>
      <section className="w-[calc(100%-17rem) h-screen ml-[17rem]">
        <Header />
        <div className="h-auto">{children}</div>
      </section>
      <section>
        <aside>
          <SideBar />
        </aside>
      </section>
    </main>
  );
}
